apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: cg4559qnb-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cg4559qnb-go 
  name: cg4559qnb-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: cg4559qnb-go 
