apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: cg4559qnb-go 
  janus-idp.io/tekton: cg4559qnb-go
  backstage.io/kubernetes-id: cg4559qnb-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: cg4559qnb-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  